name = "insanely-fast-whisper-api"
main = "src/worker.js"
compatibility_date = "2024-03-31"

[ai]
binding = "AI"

# Custom domains
[[routes]]
pattern = "api.audio.antoinemoyroud.com"
custom_domain = true

[env.production]
name = "insanely-fast-whisper-api"
route = "api.audio.antoinemoyroud.com/*" 