name = "insanely-fast-whisper-api"
main = "src/worker.js"
compatibility_date = "2024-03-31"

[[r2_buckets]]
binding = "AUDIO_BUCKET"
bucket_name = "audio-uploads"
preview_bucket_name = "audio-uploads-dev"

[vars]
ENVIRONMENT = "production"

# Use this for secrets:
# wrangler secret put MISTRAL_API_KEY

[[routes]]
pattern = "api.audio.antoinemoyroud.com"
custom_domain = true 